=== SameerFaisal/2211E2-XML/XML 2211E2 (02-05-2023)/file.dtd
<!ELEMENT class (student,student,student)>
<!ELEMENT student (firstName,lastName,school)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT school (#PCDATA)>
<!ATTLIST student id ID #REQUIRED>
<!ENTITY school "Aptech">

=== SameerFaisal/2211E2-XML/XML 2211E2 (02-05-2023)/new.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="file.css" type="text/css"?>
<!DOCTYPE class PUBLIC "public-id" "file.dtd" [
]>


<class>

<student id="s1">
<firstName>Ali</firstName>
<lastName>Haider</lastName>
<school>&gt; &lt;</school>
</student>
<student id="s2">
<firstName>Sadiq</firstName>
<lastName>Zaidi</lastName>
<school></school>
</student>
<student id="s3">
<firstName>Romaan</firstName>
<lastName>Ali</lastName>
<school></school>
</student>

</class>
